name: check_changed_labels

on: [push]

jobs:
  perform_check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: changed_files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display changed files
        run: |
          echo "Changed files: ${{ steps.changed_files.outputs.changed_files }}"
