name: check_labels

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Clone ms3
        uses: actions/checkout@v2
        with:
          repository: johentsch/ms3
          ref: workflow
          path: ./ms3
      - name: Install ms3
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ms3
      - name: Run ms3 check
        run: |
          ms3 check -f ${{ steps.files.outputs.added_modified }} --assertion --log check.log
