name: check_changed_labels

on: [push]

jobs:
  perform_check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: modified
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop if nothing was modified
        if: steps.modified.outputs.modified[0] == null
        run: exit 0
      - name: Display changed files
        run: |
          cat ${HOME}/files_modified.json
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Clone ms3
        uses: actions/checkout@v2
        with:
          repository: johentsch/ms3
          ref: workflow
          path: ./ms3
      - name: Install ms3
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ms3
      - name: Run ms3 check
        run: |
          ms3 check -f ${HOME}/files_modified.json --assertion --log check.log
