name: compare_reviewed_labels

on: pull_request

jobs:
  perform_comparison:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Clone ms3
        uses: actions/checkout@v2
        with:
          repository: johentsch/ms3
          ref: workflow
          path: ./ms3
      - name: Install ms3
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./ms3
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          path: main
          ref: ${{ github.event.pull_request.head.ref }}
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: Run ms3 check
        working-directory: ./main
        run: |
          ms3 compare -f ${{ steps.files.outputs.added_modified }}
      - name: Push comparison files
        working-directory: ./main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Added comparison files for review"
          git push
