name: zenodraft
on:
  # Trigger when you publish a release via GitHub's release page
  release:
    types: [published]
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v4
        - name: Create a draft snapshot of your repository contents as a new
                version draft in concept 7504011 on Zenodo using metadata
                from repository file .zenodo.json
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          uses: zenodraft/action@0.13.3
          with:
            concept: 7504011
            metadata: .zenodo.json
            publish: false
            sandbox: false